#!/run/current-system/sw/bin/sh

count=0
connected=""
disconnected=""

ID="$(ip link | /run/current-system/sw/bin/awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$connected Online" ; /run/current-system/sw/bin/sleep 25
        else
            echo "$connected Online" ; /run/current-system/sw/bin/sleep 25
        fi
    else
        echo "$disconnected Offline" ; /run/current-system/sw/bin/sleep 5
    fi
done
